id: P000538
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17608
  title: 西藏贵族世家 ༡༩༠༠-༡༩༥༡
  author: ''
  volumes:
    1a5fba84e0454aed9f79b756b3eb6500:
      image_group_id: I4PD4598
      title: Volume 1 of 西藏贵族世家 1900-1951
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
